Fix compile error after change to use C++23
list of compile error

/home/hpichu/work/dali-adaptor/dali/internal/adaptor/common/combined-update-render-controller.cpp: In member function ‘virtual void Dali::Internal::Adaptor::CombinedUpdateRenderController::ResizeSurface()’:
/home/hpichu/work/dali-adaptor/dali/internal/adaptor/common/combined-update-render-controller.cpp:423:5: error: ‘++’ expression of ‘volatile’-qualified type is deprecated [-Werror=volatile]
  423 |     mSurfaceResized++;

/home/hpichu/work/dali-adaptor/dali/internal/accessibility/bridge/bridge-object.cpp: In lambda function:
/home/hpichu/work/dali-adaptor/dali/internal/accessibility/bridge/bridge-object.cpp:90:167: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
   90 |     AddCoalescableMessage(static_cast<CoalescableMessages>(static_cast<int>(CoalescableMessages::PROPERTY_CHANGED_BEGIN) + static_cast<int>(event)), obj.get(), 1.0f, [=, weakObj = std::weak_ptr<Accessible>(obj)]()
      |                                                                                                                                                                       ^
/home/hpichu/work/dali-adaptor/dali/internal/accessibility/bridge/bridge-object.cpp:90:167: note: add explicit ‘this’ or ‘*this’ capture

/home/hpichu/work/dali-adaptor/automated-tests/src/dali-adaptor/utc-Dali-FileLoader.cpp:69:28: error: ambiguous overload for ‘operator==’ (operand types are ‘std::streampos’ {aka ‘std::fpos<__mbstate_t>’} and ‘int’)
   69 |   DALI_TEST_CHECK(fileSize == 0);

Change-Id: Ic4545a46b3777bec9288439f4204bf994d4df8dc
Signed-off-by: Eunki Hong <eunkiki.hong@samsung.com>